import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import SupportHeader from "@/components/SupportHeader";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <SupportHeader />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
